name: "Build Opendata website and deploy"
description: "BAM"
inputs:
  GH_TOKEN:
    description: "Github token"
    default: $
    required: true
  WEBSITE_BRANCH:
    description: "Branch to deploy the website"
    default: "gh-pages"
    required: false
runs:
  using: "composite"
  steps:
    - name: Pull OpenDataPage
      # run: git clone https://github.com/whoohoo86/gh-open-data-page.git
      uses: actions/checkout@v2
      with:
        repository: "whoohoo86/gh-open-data-page"

    - name: Create datasource.json
      uses: ./createDatasourceJsonAction
      with:
        GH_TOKEN: ${{inputs.GH_TOKEN}}

    # Runs a single command using the runners shell
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 14.x

    # Runs a set of commands using the runners shell
    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{inputs.GH_TOKEN}}
      run: |
        cd $GITHUB_WORKSPACE
        npm install
        npm run ng -- deploy --repo=https://github.com/$GITHUB_REPOSITORY.git --base-href=/${GITHUB_REPOSITORY#*/}/ --name=EckelmannF --email=EckelmannF@rki.de --branch=${{inputs.WEBSITE_BRANCH}}
